name       : libspiro
version    : 20190731
release    : 1
source     :
    - https://github.com/fontforge/libspiro/archive/20190731.tar.gz : 25678f69416115c9d5f909de4013f7a5a44a3f7ca901f912bb6de566cbb70e89
license    : GPL-3.0-or-later
component  : programming.library
summary    : simplifies the drawing of beautiful curves
description: |
    Spiro is the creation of Raph Levien. It simplifies the drawing of beautiful curves. This library will take an array of spiro control points and convert them into a series of bézier splines which can then be used in the myriad of ways the world has come to use béziers.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
