name       : libspiro
version    : '20220722'
release    : 3
source     :
    - https://github.com/fontforge/libspiro/archive/refs/tags/20220722.tar.gz : 22409086ac07b482267c5328acde1956ca84cee8b4fa6c386f89e7014ea331da
homepage   : https://github.com/fontforge/libspiro
license    : GPL-3.0-or-later
component  : programming.library
summary    : simplifies the drawing of beautiful curves
description: |
    Spiro is the creation of Raph Levien. It simplifies the drawing of beautiful curves. This library will take an array of spiro control points and convert them into a series of bézier splines which can then be used in the myriad of ways the world has come to use béziers.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
