name       : libspiro
version    : '20200505'
release    : 2
source     :
    - https://github.com/fontforge/libspiro/archive/20200505.tar.gz : 00be530b5c0ea9274baadf6c05521f0b192d4c3c1db636ac8b08efd44aaea8f5
homepage   : https://github.com/fontforge/libspiro
license    : GPL-3.0-or-later
component  : programming.library
summary    : simplifies the drawing of beautiful curves
description: |
    Spiro is the creation of Raph Levien. It simplifies the drawing of beautiful curves. This library will take an array of spiro control points and convert them into a series of bézier splines which can then be used in the myriad of ways the world has come to use béziers.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
